Make buttons use the accent color
etvascom/etvas-kit pull request #107
Opened 2021-08-09 08:45 UTC by hututudor

https://etvas.atlassian.net/browse/ETV-4298

* modify the branding provider to make variants for the accent color
* use the accent color in button variants

2021-08-09 10:42 UTC, alsofronie requested changes

2021-08-09 10:42 UTC, alsofronie commented on src/providers/BrandingService.js
> +const brandColorVariations = {
Please use `colorVariations` as single variation object and use it in both brand and accent

2021-08-09 10:42 UTC, alsofronie commented on src/providers/BrandingService.js
> +    console.warn('colors', this.cssVars)
Leftover?

2021-08-09 10:44 UTC, hututudor commented on src/providers/BrandingService.js
> +    console.warn('colors', this.cssVars)
Yes

2021-08-10 08:06 UTC, alsofronie commented on src/providers/BrandingService.js
> +  accentColorDarker: -66
```suggestion
  colorDarker: -66,
  colorLightest: 70,
  colorLighter: 45,
  colorLight: 20,
  colorDark: -33
```

2021-08-10 08:53 UTC, alsofronie requested changes
Please test my code, it is written in github

2021-08-10 08:53 UTC, alsofronie commented on src/providers/BrandingService.js
> +  colorDarker: -66
```suggestion
const colorVariations = {
  ColorLightest: 70,
  ColorLighter: 45,
  ColorLight: 20,
  ColorDark: -33,
  ColorDarker: -66
```

2021-08-10 08:53 UTC, alsofronie commented on src/providers/BrandingService.js
> +      ? this.buildColorVariants({ brandColor: updates.brandColor }, updates)
```suggestion
      ? this.buildColorVariants('brand', { brandColor: updates.brandColor }, updates)
```

2021-08-10 08:53 UTC, alsofronie commented on src/providers/BrandingService.js
> +      ? this.buildColorVariants({ accentColor: updates.accentColor }, updates)
```suggestion
      ? this.buildColorVariants('accent', { accentColor: updates.accentColor }, updates)
```

2021-08-10 08:53 UTC, alsofronie commented on src/providers/BrandingService.js
> +    )
```suggestion
  const buildColorVariants = (prefix, source, existing) =>
    Object.keys(colorVariations).reduce((colors, key) => ({
      ...colors,
      ...(existing[`${prefix}${key}`]
        ? {}
        : { [`${prefix}${key}`]: shading(src, colorVariations[key]) }
      )
    })
```

2021-08-10 10:40 UTC, alsofronie approved these changes

2021-08-10 10:40 UTC, merged