ETV-2300-new-textarea-component
etvascom/etvas-kit pull request #27
Opened 2020-08-31 14:41 UTC by elenawq

### [Jira]: https://etvas.atlassian.net/browse/ETV-2300

2020-08-31 14:58 UTC, alsofronie commented on src/TextArea/TextArea.jsx
> +  allowResize: false,
Default HTML behaviour is to allow resize.

```suggestion
  allowResize: true,
```

2020-08-31 15:09 UTC, elenawq commented on src/TextArea/TextArea.jsx
> +  noBottomSpace: PropTypes.bool,
I see that it is used in the ErrorMessage to determine whether or not we should display a small space underneath the text field

2020-08-31 15:11 UTC, elenawq commented on src/TextArea/TextArea.jsx
> +  noBottomSpace: PropTypes.bool,
This is available for Input, should we also use it in the TextArea?

2020-08-31 18:49 UTC, alsofronie commented on src/TextArea/TextArea.jsx
> +  noBottomSpace: PropTypes.bool,
My mistake

2020-08-31 18:56 UTC, alsofronie requested changes

2020-08-31 18:56 UTC, alsofronie commented on src/TextArea/ErrorMessage.jsx
> +  visibility: hidden;
Either use:

```
  return <Dummy hide={!preserveSpace} />
}

const Dummy = styled.div`
  display: ${({ hide }) => (hide ? 'none' : 'block')};
  height: 20px;
  opacity: 0;
  visibility: hidden;
```

or

```suggestion
  if (preserveSpace) {
    return <Dummy />
  }

  return null
}

const Dummy = styled.div`
  display: block;
  height: 20px;
  opacity: 0;
  visibility: hidden;
```

2020-09-01 07:44 UTC, alsofronie approved these changes

2020-09-01 07:46 UTC, merged