Add login screen
etvascom/etvas-kit pull request #58
Opened 2020-12-22 10:20 UTC by hututudor

Jira: https://etvas.atlassian.net/browse/ETK-34

2021-01-11 11:24 UTC, alsofronie requested changes

2021-01-11 11:24 UTC, alsofronie commented on src/Card/Card.variants.js
> +  tainted: {
Please use:
```suggestion
  tinted: {
```

2021-01-11 11:24 UTC, alsofronie commented on src/Form/TextField.jsx
> +      tainted={props.tainted}
```suggestion
      tinted={props.tinted}
```

2021-01-11 11:24 UTC, alsofronie commented on src/Form/TextField.jsx
> +  tainted: PropTypes.bool
```suggestion
  tinted: PropTypes.bool
```

2021-01-11 11:24 UTC, alsofronie commented on src/Form/TextField.jsx
> +  tainted: false
```suggestion
  tinted: false
```

2021-01-11 11:24 UTC, alsofronie commented on stories/LoginScreen.stories.jsx
> +export const Tainted = () => <LoginScreen tainted />
```suggestion
export const Tinted = () => <LoginScreen tinted />

```

2021-01-11 11:34 UTC, alsofronie requested changes
Please replace `tainted` with `tinted` in all your source code, not only where i've spotted them

2021-01-11 11:36 UTC, hututudor commented
Now it should be ok. Checked with grep.

2021-01-14 09:09 UTC, alsofronie approved these changes

2021-01-14 09:24 UTC, merged